import type { GaSettingsData } from "./types";
import { MAX_CONSECUTIVE_NIGHTS } from "@/lib/ga-input/constants";

export const defaultGaSettings: GaSettingsData = {
  profileKey: "default",
  profileName: "ค่าเริ่มต้น",
  isActive: true,
  populationSize: 120,
  generations: 200,
  patience: 30,
  eliteSize: 8,
  tournamentSize: 4,
  crossoverRate: 0.9,
  mutationRate: 0.004,
  fullRepairEvery: 4,
  repairEliteEvery: 8,
  randomSeed: 42,
  maxSeconds: 600,
  maxShiftsPer7Days: 10,
  weeklyMinDaysOff: 1,
  maxConsecutiveNights: MAX_CONSECUTIVE_NIGHTS,
  maxConsecutiveWorkDays: 7,
  maxTraineePerShift: 1,
  minRestHours: 8,
  targetOffDaysPerStaff: null,
  enableMorningEveningDouble: true,
  enableNightEveningDouble: true,
  preferMorningOt: true,
  morningRegularRequired: true,
  updatedAtLabel: "ยังไม่ได้บันทึกลงฐานข้อมูล",
  source: "default",
};
